# version: 2.1 # use CircleCI 2.1
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  slack: circleci/slack@4.1.3

defaults: &defaults
  environment:
    LERNA_ARGS: --concurrency 1
    CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>...<<pipeline.git.revision>>
    BASE_REF: 'master'
  working_directory: ~/project

commands:
  set_deploy_key:
    description: Sets the ssh key for project access
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0e:50:82:ad:81:17:a5:31:04:13:fd:6e:c7:72:c9:18"

  install_node_dependencies:
    description: Installs the node dependencies
    steps:
      - run: yarn install --freeze-lockfile
  

  build_package:
    description: "build a single package"
    parameters:
      pkg:
        type: string
    steps:
      - run:
          name: "Build << parameters.pkg >>"
          command: |
            yarn workspace << parameters.pkg >> build

  should_build:
    description: "Determines if a package should be built"
    parameters:
      path:
        type: string
    steps:
      - run:
          name: "Should Build << parameters.path >>"
          command: |
            SHOULD_BUILD=$(yarn entria-deploy hasChanged $CIRCLE_COMPARE_URL << parameters.path >>)
            echo $SHOULD_BUILD
            if [ "$SHOULD_BUILD" == false ]; then
                exit 0
            fi
  
  slack_notify_fail:
    description: Sends a slack notifaction on job failure
    steps:
      - slack/notify:
          branch_pattern: master
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Your job *${CIRCLE_JOB}* has failed ⚠️"
                  },
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Author*: ${CIRCLE_USERNAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*: ${CIRCLE_SHA1}"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://user-images.githubusercontent.com/26894168/101182589-31708380-3646-11eb-80d5-b174d47bf7fb.png",
                    "alt_text": "Fozzie Logo"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
  slack_notify_success:
    description: Sends a slack notifaction on job success
    steps:
      - slack/notify:
          branch_pattern: master
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Your job *${CIRCLE_JOB}* has succeeded 🎉"
                  },
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Author*: ${CIRCLE_USERNAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*: ${CIRCLE_SHA1}"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://user-images.githubusercontent.com/26894168/101182641-4220f980-3646-11eb-8782-29a6a2213815.png",
                    "alt_text": "Fozzie Logo"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
executors:
  node:
    <<: *defaults
    docker:
      # specify the version you desire here
      - image: circleci/node:12.18.4-browsers # For latest available images check – https://circleci.com/docs/2.0/docker-image-tags.json

jobs:
  set_up:
    executor: node
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run: echo "This is pipeline ID << pipeline.id >>"
      - run: echo $CIRCLE_COMPARE_URL
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
              - yarn-packages-{{ checksum "yarn.lock" }}
      - install_node_dependencies
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: # Run PR Checks
          name: Run PR Checks
          command: yarn danger ci
      - save_cache:
          name: Save Working Directory Cache
          key: working-directory-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project
                    
  conditional_build_package:
    description: "conditional build a package"
    parameters:
      pkg:
        type: string
      path:
        type: string
    executor: node
    steps:
      - restore_cache:
          name: Restore Working Directory Cache
          keys:
              - working-directory-{{ .Branch }}-{{ .Revision }}
      - should_build:
          path: << parameters.path >>
      - build_package:
          pkg: << parameters.pkg >>
    
  unit_tests:
    executor: node
    steps: # a collection of executable commands
      - restore_cache:
          name: Restore Working Directory + Bundles Cache
          keys:
              - working-directory-dist{{ .Branch }}-{{ .Revision }}
      - run: echo $CIRCLE_COMPARE_URL
      - run:
          name: "Run only needed tests"
          command: |
            FILES_CHANGED=$(yarn --silent entria-deploy changes ${CIRCLE_COMPARE_URL} --baseRef ${BASE_REF})
            echo $FILES_CHANGED
            TESTFILES=$(yarn --silent jest --findRelatedTests --listTests $FILES_CHANGED)
            echo $TESTFILES
            if [ ! -z "$TESTFILES" ];
              then
                yarn jest --passWithNoTests --coverage --forceExit --ci --maxWorkers=7 $TESTFILES
            fi

workflows:
  version: 2

  build:
    jobs:
      - set_up:
          context: web-core
          filters:
            branches:
              ignore: 'gh-pages'
      - conditional_build_package:
          path: "packages/components/atoms/f-button"
          pkg: "@justeat/f-button"
          requires:
            - set_up
      - conditional_build_package:
          path: "packages/components/atoms/f-card"
          pkg: "@justeat/f-card"
          requires:
            - set_up
      - conditional_build_package:
          path: "packages/components/organisms/f-checkout"
          pkg: "@justeat/f-checkout"
          requires:
            - set_up